"""Add Exercise, TrainingLog, Diet, and WeightLog models

Revision ID: 04ac95294efd
Revises: 42bcca336d36
Create Date: 2025-01-29 13:58:12.214322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04ac95294efd'
down_revision = '42bcca336d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weight_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_weight_log_user_id_user')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name=op.f('fk_training_log_exercise_id_exercise')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_training_log_user_id_user')),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], name=op.f('fk_training_log_workout_id_workout')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_exercise')
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diet_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_workout_diet_id_diet'), 'diet', ['diet_id'], ['id'])
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_workout_diet_id_diet'), type_='foreignkey')
        batch_op.drop_column('diet_id')

    op.create_table('user_exercise',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), nullable=False),
    sa.Column('notes', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name='fk_user_exercise_exercise_id_exercise'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_exercise_user_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('training_log')
    op.drop_table('weight_log')
    op.drop_table('diet')
    # ### end Alembic commands ###
