"""Add category and day to Exercise

Revision ID: 04c5d2232fa8
Revises: 1edf380d317b
Create Date: 2025-01-31 06:47:48.433658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c5d2232fa8'
down_revision = '1edf380d317b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=20), nullable=False, server_default='Chest'))
        batch_op.add_column(sa.Column('day', sa.String(length=10), nullable=False, server_default='Monday'))

    # Remove the default values after columns are added
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.alter_column('category', server_default=None)
        batch_op.alter_column('day', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_column('day')
        batch_op.drop_column('category')
    # ### end Alembic commands ###
