"""Added foreign key to Exercise model

Revision ID: 0e3a1835cdfb
Revises: 1bf8a830a315
Create Date: 2025-01-29 20:12:56.163598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e3a1835cdfb'
down_revision = '1bf8a830a315'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workout_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_exercise_workout_id_workout'), 'workout', ['workout_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_exercise_workout_id_workout'), type_='foreignkey')
        batch_op.drop_column('workout_id')

    # ### end Alembic commands ###
