"""Added cascading deletes and foreign key constraints

Revision ID: 1bf8a830a315
Revises: b8b0d4b3bb28
Create Date: 2025-01-29 19:51:15.111807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bf8a830a315'
down_revision = 'b8b0d4b3bb28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.alter_column('diet_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.alter_column('diet_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
