"""relationship updates

Revision ID: 1edf380d317b
Revises: cebec847df7b
Create Date: 2025-01-30 00:44:33.478000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1edf380d317b'
down_revision = 'cebec847df7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name=op.f('fk_exercise_workout_exercise_id_exercise')),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], name=op.f('fk_exercise_workout_workout_id_workout')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_workout_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_workout_log_user_id_user')),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], name=op.f('fk_user_workout_log_workout_id_workout')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('training_log')
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_constraint('fk_exercise_workout_id_workout', type_='foreignkey')
        batch_op.drop_column('workout_id')

    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.drop_constraint('fk_workout_user_id_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_workout_user_id_user', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workout_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_exercise_workout_id_workout', 'workout', ['workout_id'], ['id'])

    op.create_table('training_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), nullable=False),
    sa.Column('workout_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name='fk_training_log_exercise_id_exercise'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_training_log_user_id_user'),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], name='fk_training_log_workout_id_workout'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_workout_log')
    op.drop_table('exercise_workout')
    # ### end Alembic commands ###
