"""Add completed field to Exercise

Revision ID: 994b51cdd908
Revises: 04c5d2232fa8
Create Date: 2025-01-31 07:12:28.075168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994b51cdd908'
down_revision = '04c5d2232fa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()))
    
    # Remove the default values after columns are added
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.alter_column('completed', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_column('completed')
    # ### end Alembic commands ###
