"""Create users table

Revision ID: c62e50a6f0f4
Revises: d80cabb1803b
Create Date: 2025-02-04 12:35:09.754371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c62e50a6f0f4'
down_revision = 'd80cabb1803b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('user_diets')
    op.drop_table('exercise')
    op.drop_table('diet')
    op.drop_table('workout')
    op.drop_table('user')
    op.drop_table('exercise_workout')
    op.drop_table('user_exercises')
    op.drop_table('user_workout_log')
    op.drop_table('weight_log')
    op.drop_table('user_workouts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_workouts',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('workout_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_workouts_user_id_user'),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], name='fk_user_workouts_workout_id_workout'),
    sa.PrimaryKeyConstraint('user_id', 'workout_id')
    )
    op.create_table('weight_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('weight', sa.FLOAT(), nullable=False),
    sa.Column('notes', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_weight_log_user_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_workout_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('workout_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.VARCHAR(length=10), nullable=False),
    sa.Column('notes', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_workout_log_user_id_user'),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], name='fk_user_workout_log_workout_id_workout'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_exercises',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name='fk_user_exercises_exercise_id_exercise'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_exercises_user_id_user'),
    sa.PrimaryKeyConstraint('user_id', 'exercise_id')
    )
    op.create_table('exercise_workout',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), nullable=False),
    sa.Column('workout_id', sa.INTEGER(), nullable=False),
    sa.Column('notes', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name='fk_exercise_workout_exercise_id_exercise'),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], name='fk_exercise_workout_workout_id_workout'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=10), nullable=True),
    sa.Column('height', sa.VARCHAR(length=10), nullable=True),
    sa.Column('profile_picture', sa.VARCHAR(length=200), nullable=True),
    sa.Column('weight', sa.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('workout',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('duration', sa.INTEGER(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=80), nullable=False),
    sa.Column('completed', sa.BOOLEAN(), nullable=True),
    sa.Column('diet_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['diet_id'], ['diet.id'], name='fk_workout_diet_id_diet'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diet',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('completed', sa.BOOLEAN(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('weight', sa.VARCHAR(length=10), nullable=True),
    sa.Column('sets', sa.VARCHAR(length=10), nullable=True),
    sa.Column('reps', sa.VARCHAR(length=10), nullable=True),
    sa.Column('category', sa.VARCHAR(length=20), nullable=False),
    sa.Column('day', sa.VARCHAR(length=10), nullable=False),
    sa.Column('completed', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_diets',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('diet_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['diet_id'], ['diet.id'], name='fk_user_diets_diet_id_diet'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_diets_user_id_user'),
    sa.PrimaryKeyConstraint('user_id', 'diet_id')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
