"""Make diet_id nullable in Workout model

Revision ID: cebec847df7b
Revises: 9f0304f97da0
Create Date: 2025-01-29 21:48:38.406926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cebec847df7b'
down_revision = '9f0304f97da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.alter_column('diet_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.alter_column('diet_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
