"""Added many-to-many relationships

Revision ID: d80cabb1803b
Revises: 4ff781ae0607
Create Date: 2025-02-02 16:21:43.704136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd80cabb1803b'
down_revision = '4ff781ae0607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_diets',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('diet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diet_id'], ['diet.id'], name=op.f('fk_user_diets_diet_id_diet')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_diets_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'diet_id')
    )
    op.create_table('user_exercises',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name=op.f('fk_user_exercises_exercise_id_exercise')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_exercises_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'exercise_id')
    )
    op.create_table('user_workouts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_workouts_user_id_user')),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], name=op.f('fk_user_workouts_workout_id_workout')),
    sa.PrimaryKeyConstraint('user_id', 'workout_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_workouts')
    op.drop_table('user_exercises')
    op.drop_table('user_diets')
    # ### end Alembic commands ###
